version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      db_user: postgres
      db_pass: postgres
      db_name: postgres
      db_host: db
      db_port: 5432
    volumes:
      - .:/app  # для разработки, чтобы видеть изменения кода

  k6:
    image: grafana/k6:latest
    working_dir: /app/k6
    volumes:
      - ./k6:/app/k6
    depends_on:
      - app
    command: run --summary-trend-stats="avg,p(95),p(99)" mixed_test.js

  test:
    build: .
    depends_on:
      - db
    environment:
      db_user: postgres
      db_pass: postgres
      db_name: postgres
      db_host: db
      db_port: 5432
    volumes:
      - .:/app
    command: ["go", "test", "./...", "-v"]

volumes:
  pgdata:


